spring.application.name=StockCore
# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# POSTGRESQL DATABASE CONFIG
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/StockCore}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (OPTIONAL)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2



#email services
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key_id=${RAZORPAY_KEY_ID:}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:}

razorpay.plan.basic=plan_Sa1VOBSyE87vu1
razorpay.plan.plus=plan_Sa1W4m6e5faR4x
razorpay.plan.pro=plan_Sa1WRDUmV9Jren


gemini.api.key=${GEMINI_API_KEY:}


